[book]
authors = ["Elanora Manson", "/lgbtqia/ PDX"]
language = "en"
multilingual = false
src = "src"
title = "/lgbtqia/ PDX Guide"

[output.html]
git-repository-url = "https://github.com/elanora96/pdx-resources"
